#  ╻ ╻╻┏━┓┏━╸┏━╸╻ ╻┏━┓┏━┓╺┳┓
#  ┃╻┃┃┣┳┛┣╸ ┃╺┓┃ ┃┣━┫┣┳┛ ┃┃
#  ┗┻┛╹╹┗╸┗━╸┗━┛┗━┛╹ ╹╹┗╸╺┻┛

# default
wireguard_configuration_path: /etc/wireguard
# skip all checks
wireguard_skip_checks: no
# installs wireguard-tools
wireguard_install_tools: yes
# interface name prefix
wireguard_interface_name_prefix: wg
# list of networks with their cidrs
wireguard_networks: {}
  # k3s: 10.0.0.0/24
# ports to listen on
wireguard_ports: {}
  # k3s: 12345
# list of preshared_keys - you can set additional preshared keys per network
wireguard_preshared_keys: {}
  # bzm: ...
  # k3s: ...
# will be applied to all peers by default (if set)
wireguard_default_keepalive_seconds: no
# list of peers
wireguard_peers: {}
  # k3s:
  #   - name: host1
  #     keepalive_seconds: 0 # for disable
  #     allowed_ips:
  #       - 0.0.0.0/0
  #       - ::0
  #     endpoint: ep.com
  #   - name: host3
  #     endpoint: ep.com:1234
# list of addresses for the interface
wireguard_addresses: {}
  # k3s:
  #   host1: 10.10.10.1
  #   host3: 10.10.10.250
wireguard_keys: {}
  # k3s:
  #   host1:
  #     private: ...
  #     public: ...
  #   host3:
  #     private: ...
  #     public: ...
# optional override list for interfaces
wireguard_interfaces: {}
  # k3s: wgcutom0
# optional list of strings for the networks
wireguard_extra_config: {}
  # k3s:
  #   prestart:
  #     - echo hello
  #   poststart
  #     - echo we are online
  #   prestop:
  #     - echo time to sleep
  #   poststop:
  #     - echo we are done
# make server a VPN
wireguard_masquarade: {}
  # k3s: #eth0 or leave empty for default
# fwmarks for interfaces networks
wireguard_fwmarks: {}
  # k3s: 134
# proxy domains for these networks
wireguard_rt_tables: {}
  # k3s:
  #   name: k3s-table
  #   weight: 123
# domains to proxy using dnsmasq and NetworkManager
wireguard_proxy_domains: {}
  # k3s:
  #   # force_bash_resolver: yes
  #   list:
  #   - yandex.ru
  #   - vk.com
  #   # fwmark: random # or 2134 or do not specify it
  #   # ipset: myset
