- name: Fabulous Ansible play!
  hosts: all
  gather_facts: no
  any_errors_fatal: yes
  roles:
#  ╺┳┓┏━╸┏━╸┏━┓╻ ╻╻  ╺┳╸┏━┓
#   ┃┃┣╸ ┣╸ ┣━┫┃ ┃┃   ┃ ┗━┓
#  ╺┻┛┗━╸╹  ╹ ╹┗━┛┗━╸ ╹ ┗━┛
    - role: defaults
      tags: always
#  ╻ ╻╻┏━┓┏━╸┏━╸╻ ╻┏━┓┏━┓╺┳┓
#  ┃╻┃┃┣┳┛┣╸ ┃╺┓┃ ┃┣━┫┣┳┛ ┃┃
#  ┗┻┛╹╹┗╸┗━╸┗━┛┗━┛╹ ╹╹┗╸╺┻┛
    - role: wireguard
      tags:
        - wireguard
        - wg
