wireguard_enabled: yes
wireguard_peers:
  vpn:
  - name: public_host
    endpoint: my-vpn.example.com
    allowed_ips:
    - 0.0.0.0/0
    - ::0
    keepalive_seconds: 25
  home:
  - name: public_host
    endpoint: my-vpn.example.com
    allowed_ips:
    - "{{ wireguard_networks.home }}"
    keepalive_seconds: 25
wireguard_proxy_domains:
  vpn:
    list:
    - vk.com
    - mail.ru
    - yandex.ru
    - yandex.ua
