- name: "{{ network }} : Configure firewalld"
  include_tasks: firewalld.yml
  when: _firewalld_enabled.stdout|bool

- name: "{{ network }} : Print public keys"
  debug:
    msg: "{{ public_key }}"

- name: "{{ network }} : Add route table"
  become: yes
  blockinfile:
    marker: "# {mark} Table for wireguard network {{ network }}"
    path: /etc/iproute2/rt_tables
    block: "{{ rt_table.id }}    {{ rt_table.name }}"

- name: "{{ network }} : Save configuration"
  include_tasks: config-save.yml

#  ┬─┐┬─┐┌─┐┐ │┐ ┬
#  │─┘│┬┘│ │┌┼┘└┌┘
#  ┘  ┘└┘┘─┘┘ └ ┘ 

- name: "{{ network }} : Proxy domains install"
  include_tasks: proxy-install.yml
  when: proxy_enabled|bool

- name: "{{ network }} : Proxy domains removal"
  include_tasks: proxy-remove.yml
  when: not proxy_enabled|bool

#  ┌┐┐┬─┐┌┐┐┌┐┐┐─┐
#  │││├─  │ │││└─┐
#  ┘└┘┴─┘ ┘ ┘└┘──┘

- name: "{{ network }} : Netns install"
  include_tasks: netns-install.yml
  when: netns_enabled|bool

- name: "{{ network }} : Netns removal"
  include_tasks: netns-remove.yml
  when: not netns_enabled|bool
