- name: Set fact wireguard_attached_networks
  set_fact:
    wireguard_attached_networks: "{{ raw | from_yaml | default([]) | list }}"
  vars:
    raw: |
      {% for network, peers in wireguard_addresses.items() %}
      {% if inventory_hostname in peers.keys() %}
      - {{ network }}
      {% endif %}
      {% endfor %}

- when:
  - wireguard_enabled|bool
  - wireguard_attached_networks|length > 0
  block:
    - name: Checks
      include_tasks: checks.yml
      when: not wireguard_skip_checks|bool

    - name: Set facts
      include_tasks: facts.yml

    - name: Install wireguard-tools
      become: yes
      package:
        name: wireguard-tools
        state: latest
      when: wireguard_install_tools|bool

    - name: Allow IPv4 forwarding
      become: yes
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
      
    - name: Get firewalld state
      become: yes
      shell: firewall-cmd --state | grep -q running && echo yes || echo no
      changed_when: no
      register: _firewalld_enabled

    - name: Install wireguard
      include_tasks: install.yml
      loop: "{{ wireguard_attached_networks }}"
      loop_control:
        loop_var: network
      vars:
        address: "{{ wireguard_addresses[network][inventory_hostname] }}"
        netmask: "{{ wireguard_networks[network].split('/')[1] }}"
        cidr: "{{ address + '/' + netmask }}"
        private_key: "{{ wireguard_keys[network][inventory_hostname].private }}"
        public_key: "{{ wireguard_keys[network][inventory_hostname].public }}"
        preshared_key: "{{ wireguard_preshared_keys[network] }}"
        configuration_path: "{{ wireguard_configuration_path }}/{{ network }}"
        interface: "{{ wireguard_interfaces[network] }}"
        port: "{{ wireguard_ports[network] | int }}"
        fwmark: "{{ wireguard_fwmarks[network] }}"
        peers: "{{ wireguard_peers[network] }}"
        rt_table: "{{ wireguard_rt_tables[network] }}"
        netns_enabled: "{{ network in wireguard_netns }}"
        netns_name: "wg-{{ network }}"
        proxy_enabled: "{{ network in wireguard_proxy_domains and network not in wireguard_netns }}"
        proxy_ipset: "{{ wireguard_proxy_domains[network].ipset | default(None) }}"
        proxy_fwmark: "{{ wireguard_proxy_domains[network].fwmark | default(None) }}"
      when: network not in wireguard_disable_networks
    
    - name: Disable wireguard network
      include_tasks: uninstall.yml
      loop: "{{ wireguard_disable_networks }}"
      loop_control:
        loop_var: network
      when: network in wireguard_attached_networks

- name: Uninstall wireguard
  include_tasks: uninstall.yml
  when: not wireguard_enabled|bool
  loop: "{{ wireguard_attached_networks }}"
  loop_control:
    loop_var: network
