- name: "{{ network }}/{{ inventory_hostname }} -> {{ peer.hostname }}"
  set_fact:
    _name_prefix: "{{ network }}/{{ inventory_hostname }} -> {{ peer.hostname }}"

- when:
    - inventory_hostname == primary_peer
    - (preshared_key_name not in wireguard_preshared_keys) or
      (network in wireguard_regenerate_keys)
  block:
    - name: "{{ _name_prefix }} : Generate preshared key {{ preshared_key_name }}"
      become: yes
      shell: wg genpsk
      register: _new_preshared_key
    
    - name: "{{ _name_prefix }} : Add new preshared_key to wireguard_preshared_keys"
      set_fact:
        wireguard_preshared_keys: "{{ wireguard_preshared_keys | combine({preshared_key_name: _new_preshared_key.stdout}) }}"
      run_once: yes
