- name: "{{ network }} : Stop wireguard@{{ network }}.service"
  become: yes
  ignore_errors: yes
  systemd:
    name: "wireguard@{{ network }}.service"
    state: stopped
    enabled: no
    daemon_reload: yes

- name: "{{ network }} : Stop dns-resolver@{{ network }}.service"
  become: yes
  ignore_errors: yes
  systemd:
    name: "dns-resolver@{{ network }}.service"
    state: stopped
    enabled: no
    daemon_reload: yes
  when: network in wireguard_proxy_domains

- name: "{{ network }} : Remove network files"
  become: yes
  ignore_errors: yes
  file:
    path: "{{ wireguard_configuration_path }}/{{ network }}"
    state: absent
